---
- name: Create file.txt and write to it on all machines
  hosts: all
  tasks:
    - name: Ensure file.txt exists on Desktop
      file:
        path: "/home/{{ ansible_user }}/Desktop/file.txt"
        state: touch
        mode: '0644'

    - name: Write 'test' into file.txt
      copy:
        content: "test\n"
        dest: "/home/{{ ansible_user }}/Desktop/file.txt"
        mode: '0644'
