---
- name: Install MeshCentral Agent on Windows 10
  hosts: all
  tasks:
    - name: Download MeshCentral Agent installer
      win_get_url:
        url: http://192.168.1.16:1024/meshagents?id=4&meshid=GPIIgDm@irxPWceN@PzQC6IhEnwa0$LDmQNQvFsZEh10pttKL6rzoMzCxgZyhPv8&installflags=0
        dest: C:\Temp\meshagent-x64.exe

    - name: Install MeshCentral Agent
      win_package:
        path: C:\Temp\meshagent-x64.exe
        #product_id: "{D4A111F5-1F79-4D1D-A4A9-3AB555EC4E72}"
        state: present

    - name: Remove installer after installation
      win_file:
        path: C:\Temp\meshagent-x64.exe
        state: absent

    - name: Start MeshCentral Agent service
      win_service:
        name: MeshAgent
        state: started
        start_mode: auto

    - name: Configure MeshCentral Agent
      win_command: C:\Program Files\MeshCentral\meshagent.exe -url 192.168.1.16:3000
      args:
        creates: C:\Program Files\MeshCentral\meshagent.exe
