---
- name: Pokretanje installmesh.sh sa sudo privilegijama preko Admin usera
  hosts: all
  become: yes  # Omogućava korišćenje sudo
  vars:
    ansible_remote_tmp: /tmp
  tasks:
    - name: Pokreni meshinstall.sh skriptu sa argumentima kao root
      shell: ./meshinstall.sh https://192.168.1.16:1025 'qEthAYo$yu4xp0n9yjlRny9JJFJTKNDdJjaFaymEY9wCgKEpPK7@5l2AARxutNmu'
      args:
        chdir: /tmp
      register: install_output

    - name: Prikaži output instalacije
      debug:
        var: install_output.stdout
