---
- name: Install MeshCentral Agent on all machines using direct bash command
  hosts: all
  become: yes  # Potrebne su root privilegije za instalaciju
  tasks:
    - name: Run bash command to download and install MeshCentral agent
      shell: |
        (wget "https://192.168.1.16:1025/meshagents?script=1" --no-check-certificate -O ./meshinstall.sh || wget "https://192.168.1.16:1025/meshagents?script=1" --no-proxy --no-check-certificate -O ./meshinstall.sh) && chmod 755 ./meshinstall.sh && sudo -E ./meshinstall.sh https://192.168.1.16:1025 'RcfOz4r0lufpP4D86YgKMkEXli09jYcV1EOfKCKbEANR9bWDSliE7Q$DwwnV$ZpF' || ./meshinstall.sh https://192.168.1.16:1025 'RcfOz4r0lufpP4D86YgKMkEXli09jYcV1EOfKCKbEANR9bWDSliE7Q$DwwnV$ZpF'
      args:
        chdir: /tmp  # Preporučuje se da preuzimate skriptu u privremeni direktorijum
        warn: no      # Ignoriši upozorenja, posebno u slučaju grešaka u komandama
      register: install_output
      ignore_errors: yes  # Ako dođe do greške, playbook će nastaviti
      environment:
        HOME: /tmp
      vars:
        ansible_remote_tmp: /tmp

    - name: Output installation result
      debug:
        var: install_output.stdout  # Ispisuje izlaz iz komande
