---
- name: Pokretanje installmesh.sh sa root privilegijama preko Admin usera
  hosts: all
  remote_user: Admin         # SSH se kači kao Admin user
  become: yes                # Postaje root
  become_user: root          # Eksplicitno postaje root
  vars:
    ansible_remote_tmp: /tmp
  tasks:
    - name: Pokreni meshinstall.sh skriptu sa argumentima kao root
      shell: ./meshinstall.sh https://192.168.1.16:1025 'qEthAYo$yu4xp0n9yjlRny9JJFJTKNDdJjaFaymEY9wCgKEpPK7@5l2AARxutNmu'
      args:
        chdir: /tmp
      register: install_output

    - name: Prikaži output instalacije
      debug:
        var: install_output.stdout