---
- name: Install and start MeshCentral Agent on Windows 10
  hosts: all
  tasks:
    - name: Download MeshCentral Agent installer
      win_get_url:
        url: "http://192.168.1.16:1024/meshagents?id=4&meshid=GPIIgDm@irxPWceN@PzQC6IhEnwa0$LDmQNQvFsZEh10pttKL6rzoMzCxgZyhPv8&installflags=0"
        dest: "C:\\Temp\\meshagent-x64.exe"

    - name: Install MeshCentral Agent
      win_command: "C:\\Temp\\meshagent-x64.exe /S"  # /S za tihu instalaciju
      register: install_result
      ignore_errors: yes

    - name: Remove installer after installation
      win_file:
        path: "C:\\Temp\\meshagent-x64.exe"
        state: absent
      when: install_result.changed

    - name: Start MeshCentral Agent service
      win_service:
        name: MeshAgent
        state: started
        start_mode: auto
