---
- name: Pokretanje installmesh.sh sa argumentima kao sudo
  hosts: all
  become: yes
  tasks:
    - name: Pokreni install.sh skriptu sa argumentima
      command: ./meshinstall.sh https://192.168.1.16:1025 'asdf'
      args:
        chdir: /tmp
      register: install_output

    - name: Prikaži output instalacije
      debug:
        var: install_output.stdout