---
- name: Install MeshAgent on LinuxMint as Admin user
  hosts: all  # Ovde postaviti naziv ili IP adresu mašine
  become: yes            # Koristi sudo za komande
  become_user: Admin     # Izvrši komande kao Admin korisnik
  vars:
    ansible_remote_tmp: /tmp  # Postavljanje privremenog direktorijuma za Ansible
  tasks:
    - name: Download the MeshAgent installation script
      command: curl -k "https://192.168.1.16:1025/meshagents?script=1" -o /tmp/meshinstall.sh
      args:
        creates: /tmp/meshinstall.sh   # Ova opcija će preskočiti komandu ako je fajl već preuzet

    - name: Make the installation script executable
      command: chmod +x /tmp/meshinstall.sh
      args:
        creates: /tmp/meshinstall.sh   # Ova opcija će preskočiti komandu ako je već izvršni fajl
